-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 18:25:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- ***WorkBench importable File*** 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fitbuds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fitbuds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitbuds` DEFAULT CHARACTER SET utf8 ;
USE `fitbuds` ;

-- -----------------------------------------------------
-- Table `fitbuds`.`food_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`food_pool` (
  `food_name` VARCHAR(100) NULL,
  `food_id` VARCHAR(50) NOT NULL,
  `protein_ratio` DECIMAL(5,2) NULL,
  `calorie_ratio` DECIMAL(5,2) NULL,
  `fat_ratio` DECIMAL(5,2) NULL,
  `carb_ratio` DECIMAL(5,2) NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`dish_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`dish_pool` (
  `dish_name` DECIMAL(5,3) NULL,
  `dish_id` VARCHAR(50) NOT NULL,
  `protien_ratio` DECIMAL(5,3) NULL,
  `calorie_ratio` DECIMAL(5,3) NULL,
  `fat_ratio` DECIMAL(5,3) NULL,
  `carb_ratio` VARCHAR(45) NULL,
  `recipe` VARCHAR(50) NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`dish_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`user_details` (
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(30) NULL,
  `dob` DATETIME NULL,
  `height` DECIMAL(5,2) NULL,
  `weight` DECIMAL(5,2) NULL,
  `profile_pic` BLOB NULL,
  `gender` CHAR(1) NULL,
  `activity_level` INT NULL,
  `recommended_calori` DECIMAL(7,2) NULL,
  `diet_plan_id` VARCHAR(50) NULL,
  `workout_plan_id` VARCHAR(50) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`kilogram_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`kilogram_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`gram_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`gram_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`ounce_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`ounce_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`pound_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`pound_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`cup_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`cup_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`whole_small_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`whole_small_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`whole_medium_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`whole_medium_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`liter_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`liter_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`whole_large_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`whole_large_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`milliliter_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`milliliter_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`cubicinch_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`cubicinch_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`inch_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`inch_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`quater_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`quater_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`drop_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`drop_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`gallon_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`gallon_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`dash_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`dash_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`fluidounce_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`fluidounce_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`pint_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`pint_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`pinch_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`pinch_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`teaspoon_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`teaspoon_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`tablespoon_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`tablespoon_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`dessert_serving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`dessert_serving` (
  `id` VARCHAR(50) NOT NULL,
  `gram` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`breakfast_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`breakfast_diet` (
  `plan_id` VARCHAR(30) NULL,
  `item_id` VARCHAR(30) NULL,
  `serving_type` VARCHAR(50) NULL,
  `amount` DECIMAL(7,2) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`morning_snack_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`morning_snack_diet` (
  `plan_id` VARCHAR(30) NULL,
  `item_id` VARCHAR(30) NULL,
  `serving_type` VARCHAR(50) NULL,
  `amount` DECIMAL(7,2) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`lunch_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`lunch_diet` (
  `plan_id` VARCHAR(30) NULL,
  `item_id` VARCHAR(30) NULL,
  `serving_type` VARCHAR(50) NULL,
  `amount` DECIMAL(7,2) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`evening_snack_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`evening_snack_diet` (
  `plan_id` VARCHAR(30) NULL,
  `item_id` VARCHAR(30) NULL,
  `serving_type` VARCHAR(50) NULL,
  `amount` DECIMAL(7,2) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitbuds`.`dinner_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitbuds`.`dinner_diet` (
  `plan_id` VARCHAR(30) NULL,
  `item_id` VARCHAR(30) NULL,
  `serving_type` VARCHAR(50) NULL,
  `amount` DECIMAL(7,2) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
